train:
  
  # Basic settings
  cuda: True
  gpu_id: 0
  start_epoch: 0
  num_epochs: 100
  num_workers: 10                            # 양수로 두면 multi-process data loading
  save_summary_steps: 10
  cur_iter: 0                                # 현재까지 학습한 iteration --> domainess 설정과 tensorboard logging에 쓰임
  total_iter: 0                              # 학습해야하는 total iteration --> domainess 설정에서 사용

  # Directorys
  data_root_dir: "/mnt/hdd0/datasets/DLOW"
  checkpoint_dir: "./model/checkpoint"
  restore_dir: False                          # Fill if restoring needed
  output_dir: "/mnt/hdd0/outputs/DLOW"

  # Related to dataset
  S_nc: 3
  T_nc: 3
  resize_W: 400
  resize_H: 300
  fixed_pair: False

  # Hyperparameters
  lr: 0.00002
  beta: 0.5             # Adam optimizer hyperparameter
  n_res_blocks: 9
  lambda_cycle: 10
  lambda_ident: 10
  batch_size: 1

  # Architectures
  ngf: 64
  ndf: 32
  nef: 32
  nlatent: 16
  use_dropout: False

test:
  



